services:
  app:
    build: .
    container_name: kubernetes-go
    volumes:
    - .:/app
    ports:
    - 8080:8080
    command: sh -c "[ ! -f go.mod ] && go mod init go-kubernetes || true && go mod tidy && go run ."