apiVersion: apps/v1
kind: Deployment
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  selector:
    matchLabels:
      app: "goserver"
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: "goserver"
          image: "derivedpuma7/kubernetes-go:v5.1"

          envFrom:
            - configMapRef:
                name: goserver-env

          volumeMounts:
            - mountPath: "/app/myFamily"
              name: config

      volumes:
        - name: config
          configMap:
            name: goserver-family
            items:
            - key: members
              path: "family.txt"