apiVersion: apps/v1
kind: Deployment
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  selector:
    matchLabels:
      app: "goserver"
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: "goserver"
          image: "derivedpuma7/kubernetes-go:v5.3"

          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            periodSeconds: 5 # periodo entre cada health check
            failureThreshold: 2 # limite de falhas para considerar não health
            timeoutSeconds: 1 # limite de tempo para timeout
            successThreshold: 1 # limite de provas para considerar health

          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret

          volumeMounts:
            - mountPath: "/app/myFamily"
              name: config

      volumes:
        - name: config
          configMap:
            name: goserver-family
            items:
            - key: members
              path: "family.txt"